export const data = [
    "/home/game",
    "/home/banner",
    "/home/combatTeam",
    "/home/info",
    "/home/match",
    "/home/guessingCompetition",
    "/home/guessingCompetitionInfo",
    "/home/hotTeam",
    "/home/gcDetail",
    "/home/todayHot",
    "/home/joinTeam",
    "/home/teamIntroduction",
    "/home/infoClass",
    "/home/infoDetail",
    "/home/information",
    "/home/matchInformation",
    "/home/hotMatch",
    "/home/matchDetail",
    "/mall/commodity",
    "/mall/commodityCategory",
    "/mall/detail",
    "/circle/all",
    // "/circle/info",
    "/circle/recommend",
    "/user/sendCode",
    "/user/forgetPassword"
]